import Foundation
import AppKit

/// Installs and removes the local root CA in the macOS System keychain.
/// Uses `osascript ... with administrator privileges` so the user sees a
/// native admin password prompt instead of us asking for it ourselves.
enum CertificateInstaller {
    static let caCommonName = "Focus Shield Root CA"

    enum CertError: LocalizedError {
        case caNotFound(String)
        case scriptFailed(Int32, String)
        case proxyHelperFailed(Int32, String)
        var errorDescription: String? {
            switch self {
            case .caNotFound(let path): return "CA file not found at \(path). Try clicking 'Reinstall root CA'."
            case .scriptFailed(let code, let out): return "Admin command failed (\(code)): \(out)"
            case .proxyHelperFailed(let code, let out): return "Could not generate CA (\(code)): \(out)"
            }
        }
    }

    /// Asks the bundled proxy binary to generate the CA if missing.
    /// Returns the CA file path. Synchronous because we use it right before
    /// the install step.
    static func generateCAIfNeeded(proxyBinary: URL, dataDir: URL) throws -> URL {
        let caPath = dataDir.appendingPathComponent("ca.pem")
        if FileManager.default.fileExists(atPath: caPath.path) {
            return caPath
        }
        let proc = Process()
        proc.executableURL = proxyBinary
        proc.arguments = ["-data-dir", dataDir.path, "-gen-ca"]
        let pipe = Pipe()
        proc.standardOutput = pipe
        proc.standardError = pipe
        try proc.run()
        proc.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let out = String(data: data, encoding: .utf8) ?? ""
        if proc.terminationStatus != 0 {
            throw CertError.proxyHelperFailed(proc.terminationStatus, out)
        }
        return caPath
    }

    /// True if a cert with the same common name is currently in the
    /// System keychain. We don't try to verify trust policies — presence
    /// is enough for an onboarding hint ("looks like you've installed it").
    static func isInstalledInSystemKeychain() -> Bool {
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/security")
        proc.arguments = ["find-certificate", "-c", caCommonName, "/Library/Keychains/System.keychain"]
        let null = Pipe()
        proc.standardOutput = null
        proc.standardError = null
        do {
            try proc.run()
        } catch {
            return false
        }
        proc.waitUntilExit()
        return proc.terminationStatus == 0
    }

    /// Run the trust-install command with an admin prompt.
    ///
    /// macOS 26 (Tahoe) tightened SecTrustSettingsSetTrustSettings: it now
    /// rejects calls whose originating GUI app is unsigned with
    /// "authorization denied since no user interaction was possible".
    /// `swiftc`-built bundles like ours fall into that bucket. To work
    /// around it we hand the trust step to Terminal.app (Apple-signed and
    /// therefore accepted by trustd) by opening a `.command` file that
    /// runs `sudo security add-trusted-cert`. Terminal prompts for the
    /// sudo password; we poll the System keychain to detect completion.
    static func installAndTrust(caPath: URL) throws {
        guard FileManager.default.fileExists(atPath: caPath.path) else {
            throw CertError.caNotFound(caPath.path)
        }

        let scriptPath = try writeInstallCommandScript(caPath: caPath)
        defer { try? FileManager.default.removeItem(at: scriptPath) }

        let opener = Process()
        opener.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        opener.arguments = [scriptPath.path]
        try opener.run()
        opener.waitUntilExit()
        if opener.terminationStatus != 0 {
            throw CertError.scriptFailed(opener.terminationStatus, "Could not open Terminal to install the certificate.")
        }

        // Terminal runs async — wait up to 90s for the cert to land in the
        // System keychain. Long enough to type a sudo password without
        // pressure, short enough that an abandoned flow surfaces an error.
        let deadline = Date().addingTimeInterval(90)
        while Date() < deadline {
            if isInstalledInSystemKeychain() { return }
            Thread.sleep(forTimeInterval: 0.5)
        }
        throw CertError.scriptFailed(1, "Install didn't finish. Did you close Terminal before entering your password?")
    }

    private static func writeInstallCommandScript(caPath: URL) throws -> URL {
        let body = """
        #!/bin/bash
        # Auto-generated by Focus Shield. Closes when the install finishes.
        echo "Focus Shield needs to add its local CA to the System keychain."
        echo "macOS will ask for your password."
        echo
        if sudo /usr/bin/security add-trusted-cert -d -r trustRoot \\
            -k /Library/Keychains/System.keychain \\
            \(shellEscape(caPath.path)); then
            echo
            echo "Done — you can close this window."
        else
            echo
            echo "Install failed. Leave this window open so you can read the error."
            read -n 1 -s -r -p "Press any key to close."
        fi
        sleep 1
        """
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("focus-shield-install-ca.command")
        try? FileManager.default.removeItem(at: tmp)
        try body.write(to: tmp, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o755], ofItemAtPath: tmp.path
        )
        return tmp
    }

    /// Remove the cert from the keychain (admin prompt). Also wipes the
    /// pre-rename "Bad Habit Blocker Root CA" so a single reset is enough
    /// after upgrading from the old name. `|| true` keeps the command
    /// successful when the legacy cert isn't present.
    static func uninstallFromKeychain() throws {
        let current = "/usr/bin/security delete-certificate -c " +
            shellEscape(caCommonName) + " /Library/Keychains/System.keychain"
        let legacy = "/usr/bin/security delete-certificate -c " +
            shellEscape("Bad Habit Blocker Root CA") + " /Library/Keychains/System.keychain || true"
        let shellCmd = "(\(current)) ; \(legacy)"
        try runAdmin(shell: shellCmd, prompt: "Focus Shield wants to remove its local certificate from the System keychain.")
    }

    // MARK: -

    private static func runAdmin(shell: String, prompt: String) throws {
        // osascript -e 'do shell script "..." with administrator privileges
        //   with prompt "..."'
        let escapedShell = appleScriptEscape(shell)
        let escapedPrompt = appleScriptEscape(prompt)
        let script = "do shell script \"\(escapedShell)\" with administrator privileges with prompt \"\(escapedPrompt)\""

        // SecTrustSettingsSetTrustSettings (invoked inside `security
        // add-trusted-cert`) refuses to show its consent dialog when the
        // calling app is LSUIElement — the user sees "authorization was
        // denied since no user interaction was possible". Briefly flip to
        // a regular foreground app for the duration of the admin call.
        let restoreActivation = pushForegroundActivation()
        defer { restoreActivation() }

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        proc.arguments = ["-e", script]
        let pipe = Pipe()
        proc.standardOutput = pipe
        proc.standardError = pipe
        try proc.run()
        proc.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let out = String(data: data, encoding: .utf8) ?? ""
        if proc.terminationStatus != 0 {
            throw CertError.scriptFailed(proc.terminationStatus, out)
        }
    }

    private static func pushForegroundActivation() -> () -> Void {
        var previous: NSApplication.ActivationPolicy = .accessory
        let flip = {
            previous = NSApp.activationPolicy()
            NSApp.setActivationPolicy(.regular)
            NSApp.activate(ignoringOtherApps: true)
        }
        if Thread.isMainThread {
            flip()
        } else {
            DispatchQueue.main.sync(execute: flip)
        }
        return {
            DispatchQueue.main.async {
                NSApp.setActivationPolicy(previous)
            }
        }
    }

    private static func shellEscape(_ s: String) -> String {
        // Single-quoted; embed any literal quotes by closing/escaping.
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static func appleScriptEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
